# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Ferris Sweep DGG'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["ferris/sweep"]'
      alphas: '["qwerty"]'
      nav: '["vi"]'
      clipboard: '["mac"]'
      layers: '["default"]'
